name = "yarnworker"
type = "javascript"
account_id = "your-account-id" # Replace with your Cloudflare account ID
workers_dev = true

[env.production]
zone_id = "your-zone-id" # Replace with your Cloudflare zone ID
route = "https://your-domain.com/*" # Replace with your domain

[vars]
YARN_DATA = "YARN_DATA"

[kv_namespaces]
[[kv_namespaces]]
binding = "YARN_DATA"
id = "your-kv-namespace-id" # Replace with your KV namespace ID

[build]
upload = { main = "src/worker.js" }

[observability.logs]
enabled = true